### ISSUE TITLE
bsm.osim file has no skeleton

### ISSUE THREAD

**Issue by yinyunie** [MarilynKeller/aitviewer-skel#1]
Hi Marilyn,

Thanks a lot for sharing this nice work!

When I run `python load_osim.py --osim /path/to/bsm.osim`, there is a bug trigged in this [line](https://github.com/MarilynKeller/aitviewer-skel/blob/4cf87d1a7c6f86affbee85126d43b8d8db69de91/aitviewer/renderables/osim.py#L298), saying that the `osim` file loaded by nimble does not has the `skeleton` property: `AttributeError: 'NoneType' object has no attribute 'getPositions`.

Could you please help with this?  Thanks a lot.

Best regards,
Yinyu

**Comment by MarilynKeller** [comment]
Hi, thanks for your interest in our work.

Most likely the script did not manage to load the bsm.osim. 
Note that you should first download the .bsm file from the download page [here](https://skel.is.tue.mpg.de/index.html) , then change `/path/to/bsm.osim` to the actual path to this file on your computer.

I just made a code push to make the error clearer, I suggest you run `git pull` and retry.

**Comment by MarilynKeller** [comment]
I see, thanks for the clarification. I am using an older version of nimble, can you try with this:
`pip install nimblephysics==0.10.32`

**Comment by yinyunie** [comment]
Thanks Marilyn. I tried nimblephysics at 0.10.32, but the bug remains there. Not sure if there is something missing in `bsm.osm` file.

**Comment by MarilynKeller** [comment]
I just uploaded a new version of bsm.osim, can you re-download the model from https://skel.is.tue.mpg.de/download.php and try again?
![image](https://github.com/MarilynKeller/aitviewer-skel/assets/102662583/16a108f8-8f7b-4028-b4b1-9c384523b138)

**Comment by yinyunie** [comment]
Thanks Marilyn. I think I found the issue.

nimblephysics can not read the `bsm.osm` file from a hyperlinked directory. I should give the real file address like below, and then it runs successfully.

```
python load_osim.py --osim real_address_of_bsm.osim
```
![frame_000000](https://github.com/MarilynKeller/aitviewer-skel/assets/25686434/9935b0b9-a19b-463a-bb42-64aec6390684)

Thanks a lot for your help!

**Comment by MarilynKeller** [comment]
I see, I observed the same issue, it was not supporting relative path. I just pushed a fix. Thanks for pointing this out.
